# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qingtian_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default=b'\xe8\xae\xb8\xe5\x81\xa5', max_length=20),
        ),
    ]
