# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qingtian_blog', '0007_auto_20160725_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_tag',
            field=models.CharField(default='hello', max_length=20),
        ),
    ]
