# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qingtian_blog', '0008_blog_blog_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('C#base', 'C#base'), ('C#advance', 'C#advance'), ('Bootstrap', 'Bootstrap'), ('ubuntu', 'ubuntu')], max_length=20),
        ),
    ]
