# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-08 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qingtian_blog', '0011_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('C#', 'C#\u5c0f\u8bb0'), ('python', 'python'), ('webFront', '\u524d\u7aef'), ('linux', 'linux'), ('datastruct', '\u6570\u636e\u7ed3\u6784')], max_length=20),
        ),
    ]
