# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-03 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qingtian_blog', '0012_auto_20160908_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(default='updloadfile', max_length=50),
        ),
    ]
